# Generated by Django 4.2.14 on 2024-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
