# Generated by Django 5.0.7 on 2024-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='end_num',
            new_name='max_num',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
