# Generated by Django 5.0.7 on 2024-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('num_games', '0002_rename_end_num_game_max_num_remove_game_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
