# Generated by Django 4.2.14 on 2024-08-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('num_games', '0003_alter_game_date_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='end_num',
            new_name='max_num',
        ),
    ]
